apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: myhpamem
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mydeploy
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 2  # If this doesnt work reduce the % to 2-4%
