apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: emptyDir1
  name: emptydirectory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emptyDir1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: emptyDir1
    spec:
      containers:
        - name: cont1
          image: centos
          volumeMounts:
            - mountPath: /tmp/data
              name: emptydirvol
        - name: cont2
          image: ubuntu
          volumeMounts:
            - mountPath: /tmp/cache
              name: emptydirvol
      volumes:
        - name: emptydirvol
          emptyDir: {}
