apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: emptyDir1
  name: emptyDirExample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emptyDir1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: emptyDir1
    spec:
      containers:
        - name: C01
          image: registry.k8s.io/test-webserver
          volumeMounts:
            - mountPath: /tmp/data
              name: empty-dir
        - name: C02
          image: registry.k8s.io/test-webserver
          volumeMounts:
            - mountPath: /tmp/cache
              name: emptyDirExample
      volumes:
        - name: emptyDirExample
          emptyDir: {}
