apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hostPath1
  name: hostpath1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hostPath1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hostPath1
    spec:
      containers:
        - name: hostpath1
          image: ubuntu
          command: [ "/bin/bash", "-c", "sleep 10000" ]
          volumeMounts:
            - mountPath: "/usr/share"
              name: task-pv-storage
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
