kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: demodaemonset
spec:
  selector:      # matches the labels in template.metadata.labels
    matchLabels:
      name: daemon
  template:      # pod template
    metadata:
      name: testpod
      labels:
        name: daemon
    spec:
      containers:
        - name: c01
          image: ubuntu  # ubuntu:22.10
          command: ["/bin/bash", "-c", "while true; do echo Hello World; sleep 5; done"]